const TODO_ADD = 'TODO_ADD';
const TODO_REMOVE = 'TODO_REMOVE';
const TODO_EDIT = 'TODO_EDIT';
const TODO_TOGGLE = 'TODO_TOGGLE';

module.exports = {
  TODO_ADD,
  TODO_REMOVE,
  TODO_EDIT,
  TODO_TOGGLE,
};
