const TODO_BOOT = 'TODO_BOOT';
const TODO_ADD = 'TODO_ADD';
const TODO_EDIT = 'TODO_EDIT';
const TODO_TOGGLE = 'TODO_TOGGLE';
const TODO_REMOVE = 'TODO_REMOVE';

module.exports = {
  TODO_BOOT,
  TODO_ADD,
  TODO_EDIT,
  TODO_TOGGLE,
  TODO_REMOVE,
};
